# Generated by Django 2.2.5 on 2020-03-09 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa_institucion',
            fields=[
                ('id_emp_inst', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_emp_inst', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flp_trafico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_amhs', models.CharField(max_length=30)),
                ('fecha_llegada', models.DateField()),
                ('hora_amhs', models.CharField(max_length=10)),
                ('prioridad', models.CharField(max_length=2)),
                ('id_plan', models.CharField(max_length=50)),
                ('transponder', models.CharField(max_length=60)),
                ('origen', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=250)),
                ('visto', models.BooleanField(default=False)),
                ('visto_por', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Metar_trafico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_amhs', models.CharField(max_length=30)),
                ('fecha_llegada', models.DateField()),
                ('hora_amhs', models.CharField(max_length=10)),
                ('prioridad', models.CharField(max_length=2)),
                ('estacion', models.CharField(max_length=50)),
                ('hora_clima', models.CharField(max_length=60)),
                ('texto', models.CharField(max_length=1000)),
                ('visto', models.BooleanField(default=False)),
                ('visto_por', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta_flp',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(max_length=25)),
                ('ruta', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('ci', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ManyToManyField(to='plan_vuelo.Cargo')),
                ('empresa_institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.Empresa_institucion')),
            ],
        ),
        migrations.CreateModel(
            name='EntrePuntos_flp',
            fields=[
                ('id_segmento', models.AutoField(primary_key=True, serialize=False)),
                ('puntoInicial', models.CharField(max_length=35)),
                ('puntoFinal', models.CharField(max_length=35)),
                ('distancia', models.IntegerField()),
                ('nivelCrucero', models.CharField(max_length=6)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_vuelo.Ruta_flp')),
            ],
            options={
                'ordering': ['id_segmento', 'ruta'],
            },
        ),
        migrations.CreateModel(
            name='Flp_aprobado',
            fields=[
                ('id_flp_aprobado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='plan_vuelo.Flp_trafico')),
                ('fecha_aprob', models.DateField()),
                ('hora_aprob', models.TimeField(auto_now=True)),
                ('transponder', models.IntegerField()),
                ('ruta_usada', models.CharField(max_length=250)),
                ('puntos_de_ficha', models.CharField(max_length=400)),
                ('matricula', models.CharField(max_length=400)),
                ('controlador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.Trabajador')),
                ('metar_trafico', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.Metar_trafico')),
            ],
        ),
    ]
