# Generated by Django 2.2.5 on 2020-05-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='codigo',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
