# Generated by Django 3.1.5 on 2021-01-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_vuelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacional',
            fields=[
                ('id_comunicacion', models.AutoField(primary_key=True, serialize=False)),
                ('direcciones_amhs', models.CharField(max_length=100)),
                ('originador_amhs', models.CharField(max_length=8)),
                ('fecha_hora_deposito', models.CharField(max_length=6)),
                ('tiempo_utc_modific', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Operacional',
            fields=[
                ('id_operacional', models.AutoField(primary_key=True, serialize=False)),
                ('id_aeronave', models.CharField(max_length=7)),
                ('regla_vuelo', models.CharField(max_length=1)),
                ('tipo_vuelo', models.CharField(max_length=1)),
                ('numero', models.CharField(max_length=2)),
                ('tipo_aeronave', models.CharField(max_length=4)),
                ('estela_turbulenta', models.CharField(max_length=1)),
                ('equipoA', models.CharField(max_length=100)),
                ('equipoB', models.CharField(max_length=100)),
                ('aerodromo_salida', models.CharField(max_length=4)),
                ('hora_salida', models.CharField(max_length=4)),
                ('velocidad_crucero_cat', models.CharField(max_length=1)),
                ('velocidad_crucero', models.CharField(max_length=5)),
                ('nivel_cat', models.CharField(max_length=1)),
                ('nivel', models.CharField(max_length=4)),
                ('ruta', models.CharField(max_length=100)),
                ('aerodromo_destino', models.CharField(max_length=4)),
                ('total_eet', models.CharField(max_length=4)),
                ('aerodromo_alterno', models.CharField(blank=True, max_length=4)),
                ('aerodromo_alterno2', models.CharField(blank=True, max_length=4)),
                ('otros_datos', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Suplementaria',
            fields=[
                ('id_suplementaria', models.AutoField(primary_key=True, serialize=False)),
                ('autonomia_hr_min', models.CharField(max_length=4)),
                ('personas_bordo', models.CharField(max_length=3)),
                ('equipo_radio_uhf', models.BooleanField(default=False)),
                ('equipo_radio_vhf', models.BooleanField(default=False)),
                ('equipo_radio_elt', models.BooleanField(default=False)),
                ('equipo_superv', models.BooleanField(default=False)),
                ('equipo_superv_polar', models.BooleanField(default=False)),
                ('equipo_superv_deser', models.BooleanField(default=False)),
                ('equipo_superv_mar', models.BooleanField(default=False)),
                ('equipo_superv_jung', models.BooleanField(default=False)),
                ('chaleco', models.BooleanField(default=False)),
                ('chaleco_luz', models.BooleanField(default=False)),
                ('chaleco_fluor', models.BooleanField(default=False)),
                ('chaleco_uhf', models.BooleanField(default=False)),
                ('chaleco_vhf', models.BooleanField(default=False)),
                ('nro_botes', models.IntegerField(blank=True)),
                ('capacidad_botes', models.CharField(blank=True, max_length=3)),
                ('color_bote', models.CharField(blank=True, max_length=30)),
                ('color_marca_avion', models.CharField(max_length=70)),
                ('obs', models.CharField(blank=True, max_length=100)),
                ('piloto', models.CharField(max_length=60)),
                ('requisitos_adic', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_vuelo_presentado',
            fields=[
                ('id_fpl_presentado', models.AutoField(primary_key=True, serialize=False)),
                ('nro_formulario', models.IntegerField()),
                ('fecha_presentacion', models.DateField()),
                ('hora_presentacion', models.CharField(max_length=10)),
                ('arg_rechazo_policia', models.CharField(blank=True, max_length=50)),
                ('arg_rechazo_ais', models.CharField(blank=True, max_length=50)),
                ('date_estado_ais', models.CharField(blank=True, max_length=200)),
                ('date_estado_policia', models.CharField(blank=True, max_length=200)),
                ('hora_cancel_expir', models.CharField(blank=True, max_length=10)),
                ('fk_ais', models.ForeignKey(blank=True, db_column='fk_ais_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ais+', to='plan_vuelo.trabajador')),
                ('fk_comunicador', models.ForeignKey(blank=True, db_column='fk_comunicador_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='com+', to='plan_vuelo.trabajador')),
                ('fk_despachador', models.ForeignKey(db_column='fk_despachador_id', on_delete=django.db.models.deletion.PROTECT, related_name='despa+', to='plan_vuelo.trabajador')),
                ('fk_estado', models.ForeignKey(db_column='fk_estado_id', on_delete=django.db.models.deletion.PROTECT, related_name='estado+', to='generacion_fpl.estado')),
                ('fk_policia', models.ForeignKey(blank=True, db_column='fk_policia_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poli+', to='plan_vuelo.trabajador')),
                ('parte_comunicacional', models.OneToOneField(blank=True, db_column='parte_comunicacional_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcomunic+', to='generacion_fpl.comunicacional')),
                ('parte_operacional', models.OneToOneField(blank=True, db_column='parte_operacional_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poperac+', to='generacion_fpl.operacional')),
                ('parte_suplementaria', models.OneToOneField(blank=True, db_column='parte_suplementaria_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psuple+', to='generacion_fpl.suplementaria')),
            ],
        ),
    ]
