# Generated by Django 2.2.5 on 2020-05-03 03:16

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajadoresATS',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.IntegerField(blank=True)),
                ('ci_extension', models.TextField(blank=True)),
                ('a_paterno', models.TextField(blank=True)),
                ('a_materno', models.TextField(blank=True)),
                ('a_casada', models.TextField(blank=True)),
                ('p_nombre', models.TextField(blank=True)),
                ('s_nombre', models.TextField(blank=True)),
                ('nacionalidad', models.TextField(blank=True)),
                ('sexo', models.TextField(blank=True)),
                ('id_item', models.IntegerField(blank=True)),
                ('id_seccion', models.IntegerField(blank=True)),
                ('id_seccionactual', models.IntegerField(blank=True)),
                ('tipo_trabajador', models.TextField(blank=True)),
                ('foto', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/var/www/nuclear/appBoson/sistema_aasana/back-end/server/uploads/fotografias'), upload_to='')),
                ('correo', models.TextField(blank=True)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.TextField(blank=True)),
                ('celular', models.TextField(blank=True)),
                ('direccion', models.TextField(blank=True)),
                ('id_sueldo', models.IntegerField(blank=True)),
                ('id_cargo', models.IntegerField(blank=True)),
                ('activo', models.BooleanField(default=False)),
                ('areat', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'trabajadores',
            },
        ),
        migrations.CreateModel(
            name='CuentasATS',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('id_rol', models.IntegerField(blank=True)),
                ('usuario', models.TextField(blank=True)),
                ('password', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=False)),
                ('resetPasswordToken', models.TextField(blank=True)),
                ('resetPasswordExpires', models.DateField()),
                ('id_trabajador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trabajadoresATS.TrabajadoresATS')),
            ],
            options={
                'db_table': 'cuentas',
            },
        ),
    ]
