# Generated by Django 2.2.5 on 2020-05-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadoresATS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentasats',
            name='password',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='cuentasats',
            name='resetPasswordToken',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='cuentasats',
            name='usuario',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='a_casada',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='a_materno',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='a_paterno',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='areat',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='celular',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='ci_extension',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='correo',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='direccion',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='p_nombre',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='s_nombre',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='sexo',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='telefono',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='trabajadoresats',
            name='tipo_trabajador',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
