# Generated by Django 3.1.5 on 2021-01-13 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_vuelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abreviatura_8400',
            fields=[
                ('abreviatura', models.CharField(max_length=550, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('abreviatura',),
            },
        ),
        migrations.CreateModel(
            name='Asunto',
            fields=[
                ('id_asunto', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion_asunto', models.CharField(max_length=350)),
                ('fraseologia_asunto', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('id_asunto',),
            },
        ),
        migrations.CreateModel(
            name='Letra_asunto',
            fields=[
                ('id_letra', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('titulo_letra', models.CharField(max_length=350)),
                ('acronimo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('id_letra',),
            },
        ),
        migrations.CreateModel(
            name='Pib_trafico',
            fields=[
                ('ref_notam_amhs', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='plan_vuelo.notam_trafico')),
                ('decodificado', models.CharField(max_length=600)),
                ('publicado', models.DateTimeField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=False)),
                ('archivado', models.BooleanField(default=False)),
                ('pendiente', models.BooleanField(default=True)),
                ('msj_publicado', models.CharField(blank=True, max_length=600, null=True)),
                ('instalacion', models.CharField(blank=True, max_length=60, null=True)),
                ('oficialaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.trabajador')),
            ],
            options={
                'ordering': ['ref_notam_amhs'],
            },
        ),
        migrations.CreateModel(
            name='Simbolo_8400',
            fields=[
                ('id_simbolo', models.AutoField(primary_key=True, serialize=False)),
                ('simbolo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('id_simbolo',),
            },
        ),
        migrations.CreateModel(
            name='Pib_extenso',
            fields=[
                ('notam_extenso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='aro_ais.pib_trafico')),
                ('notam_id', models.CharField(blank=True, max_length=70, null=True)),
                ('notam_tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('ref_notam_id', models.CharField(blank=True, max_length=10, null=True)),
                ('fir', models.CharField(blank=True, max_length=10, null=True)),
                ('notam_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_trafico', models.CharField(blank=True, max_length=50, null=True)),
                ('proposito', models.CharField(blank=True, max_length=200, null=True)),
                ('alcance', models.CharField(blank=True, max_length=100, null=True)),
                ('fl_inferior', models.IntegerField(blank=True, null=True)),
                ('fl_superior', models.IntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('valid_desde', models.DateTimeField(blank=True, null=True)),
                ('valid_hasta', models.DateTimeField(blank=True, null=True)),
                ('agendado', models.CharField(blank=True, max_length=150, null=True)),
                ('cuerpo', models.CharField(blank=True, max_length=400, null=True)),
                ('limit_superior', models.CharField(blank=True, max_length=10, null=True)),
                ('limit_inferior', models.CharField(blank=True, max_length=10, null=True)),
                ('indices_item_a', models.CharField(blank=True, max_length=15, null=True)),
                ('indices_item_b', models.CharField(blank=True, max_length=15, null=True)),
                ('indices_item_c', models.CharField(blank=True, max_length=15, null=True)),
                ('indices_item_d', models.CharField(blank=True, max_length=15, null=True)),
                ('indices_item_e', models.CharField(blank=True, max_length=15, null=True)),
                ('indices_item_f', models.CharField(blank=True, max_length=15, null=True)),
                ('indices_item_g', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['notam_id'],
            },
        ),
        migrations.CreateModel(
            name='Significado_8400',
            fields=[
                ('id_significado', models.AutoField(primary_key=True, serialize=False)),
                ('significado_completo', models.CharField(max_length=500)),
                ('significado_pib', models.CharField(max_length=400)),
                ('abreviatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.abreviatura_8400')),
            ],
        ),
        migrations.CreateModel(
            name='Pib_registro_documento',
            fields=[
                ('id_registropib', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('oficialaro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.trabajador')),
                ('registro', models.ManyToManyField(to='aro_ais.Pib_trafico')),
            ],
            options={
                'ordering': ['fecha_generado'],
            },
        ),
        migrations.CreateModel(
            name='Estado_asunto',
            fields=[
                ('id_estado_asunto', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=350)),
                ('fraseologia_estado', models.CharField(blank=True, max_length=150, null=True)),
                ('id_asunto', models.ManyToManyField(to='aro_ais.Asunto')),
            ],
            options={
                'ordering': ('id_estado_asunto',),
            },
        ),
        migrations.AddField(
            model_name='asunto',
            name='letra_asunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.letra_asunto'),
        ),
        migrations.AddField(
            model_name='abreviatura_8400',
            name='simbolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.simbolo_8400'),
        ),
    ]
