# Generated by Django 3.1.1 on 2020-09-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_vuelo', '0027_auto_20200927_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pib_trafico',
            fields=[
                ('pib_notam', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='plan_vuelo.notam_trafico')),
                ('fir', models.CharField(max_length=20)),
                ('instalacion', models.CharField(max_length=30)),
                ('informacion', models.CharField(max_length=900)),
                ('publicado', models.BooleanField(default=False)),
                ('vigente', models.BooleanField(default=False)),
                ('archivado', models.BooleanField(default=False)),
                ('inicio_publi', models.DateField()),
                ('fin_publi', models.DateField()),
                ('oficialaro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.trabajador')),
            ],
            options={
                'ordering': ['fir'],
            },
        ),
    ]
