# Generated by Django 3.1.1 on 2020-09-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pib_trafico',
            name='archivado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pib_trafico',
            name='fin_publi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pib_trafico',
            name='inicio_publi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pib_trafico',
            name='publicado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pib_trafico',
            name='vigente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
