# Generated by Django 3.1.5 on 2021-02-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abreviatura_8400',
            name='abreviatura',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
