# Generated by Django 3.1.5 on 2021-02-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0002_auto_20210219_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abreviatura_8400',
            name='simbolo',
        ),
        migrations.AddField(
            model_name='abreviatura_8400',
            name='simbolo',
            field=models.ManyToManyField(to='aro_ais.Simbolo_8400'),
        ),
    ]
