# Generated by Django 3.1.1 on 2020-09-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0027_auto_20200927_0018'),
        ('aro_ais', '0003_auto_20200927_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pib_trafico',
            name='oficialaro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.trabajador'),
        ),
    ]
