# Generated by Django 3.1.5 on 2021-03-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0004_historico_pib'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico_pib',
        ),
    ]
