# Generated by Django 3.1.1 on 2020-09-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0006_auto_20200927_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pib_trafico',
            name='publicadofecha',
        ),
    ]
