# Generated by Django 3.1.1 on 2020-09-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0010_pib_trafico_publicado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pib_extenso',
        ),
    ]
