# Generated by Django 2.2.5 on 2021-03-23 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0011_auto_20210323_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco_notam_charly',
            name='tipo_notam',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='aro_ais.Tipo_notam'),
            preserve_default=False,
        ),
    ]
