# Generated by Django 3.1.1 on 2020-09-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0011_delete_pib_extenso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pib_extenso',
            fields=[
                ('notam_extenso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='aro_ais.pib_trafico')),
                ('notam_id', models.CharField(max_length=10)),
                ('notam_tipo', models.CharField(max_length=10)),
                ('ref_notam_id', models.CharField(max_length=10)),
                ('fir', models.CharField(max_length=10)),
                ('notam_codigo', models.CharField(max_length=10)),
                ('tipo_trafico', models.CharField(max_length=50)),
                ('proposito', models.CharField(max_length=200)),
                ('alcance', models.CharField(max_length=100)),
                ('fl_inferior', models.IntegerField()),
                ('fl_superior', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=50)),
                ('valid_desde', models.DateTimeField(blank=True, null=True)),
                ('valid_hasta', models.DateTimeField(blank=True, null=True)),
                ('agendado', models.CharField(max_length=150)),
                ('cuerpo', models.CharField(max_length=400)),
                ('limit_superior', models.CharField(max_length=10)),
                ('limit_inferior', models.CharField(max_length=10)),
                ('indices_item_a', models.CharField(max_length=15)),
                ('indices_item_b', models.CharField(max_length=15)),
                ('indices_item_c', models.CharField(max_length=15)),
                ('indices_item_d', models.CharField(max_length=15)),
                ('indices_item_e', models.CharField(max_length=15)),
                ('indices_item_f', models.CharField(max_length=15)),
                ('indices_item_g', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['notam_id'],
            },
        ),
    ]
