# Generated by Django 2.2.5 on 2021-03-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0012_banco_notam_charly_tipo_notam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='serie_numero_alfa',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='serie_numero_alfa_cancel',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='serie_numero_alfa_repla',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='serie_numero_charly',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='serie_numero_charly_cancel',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='serie_numero_charly_repla',
            field=models.CharField(max_length=80),
        ),
    ]
