# Generated by Django 2.2.5 on 2021-03-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0013_auto_20210323_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_notam',
            name='tipo_notam',
            field=models.CharField(max_length=21, primary_key=True, serialize=False),
        ),
    ]
