# Generated by Django 3.1.1 on 2020-09-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0014_modelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MODELNAME',
        ),
    ]
