# Generated by Django 2.2.5 on 2021-03-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0014_auto_20210323_0340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banco_notam_charly',
        ),
        migrations.DeleteModel(
            name='Direccion_amhs',
        ),
        migrations.DeleteModel(
            name='Prioridad',
        ),
        migrations.DeleteModel(
            name='Tipo_notam',
        ),
    ]
