# Generated by Django 2.2.5 on 2021-03-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0016_banco_notam_charly_direccion_amhs_prioridad_tipo_notam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banco_notam_charly',
        ),
    ]
