# Generated by Django 3.1.7 on 2021-03-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0019_banco_notam_charly_direccion_amhs_prioridad_tipo_notam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion_amhs',
            options={'ordering': ('direccionamiento',)},
        ),
        migrations.AlterModelOptions(
            name='prioridad',
            options={'ordering': ('prioridad',)},
        ),
        migrations.AlterModelOptions(
            name='tipo_notam',
            options={'ordering': ('tipo_notam',)},
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='codigo_notam_asunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.asunto'),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='codigo_notam_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.estado_asunto'),
        ),
    ]
