# Generated by Django 3.1.7 on 2021-03-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0020_auto_20210323_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie_notam',
            fields=[
                ('serie_notam', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('serie_notam',),
            },
        ),
        migrations.AlterModelOptions(
            name='banco_notam_charly',
            options={'ordering': ('tipo_notam',)},
        ),
        migrations.RemoveField(
            model_name='banco_notam_charly',
            name='serie_numero_alfa',
        ),
        migrations.RemoveField(
            model_name='banco_notam_charly',
            name='serie_numero_alfa_cancel',
        ),
        migrations.RemoveField(
            model_name='banco_notam_charly',
            name='serie_numero_alfa_repla',
        ),
        migrations.RemoveField(
            model_name='banco_notam_charly',
            name='serie_numero_charly',
        ),
        migrations.RemoveField(
            model_name='banco_notam_charly',
            name='serie_numero_charly_cancel',
        ),
        migrations.RemoveField(
            model_name='banco_notam_charly',
            name='serie_numero_charly_repla',
        ),
        migrations.AddField(
            model_name='banco_notam_charly',
            name='correlativo',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco_notam_charly',
            name='referencia_notam',
            field=models.CharField(default=123, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco_notam_charly',
            name='serie',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.PROTECT, to='aro_ais.serie_notam'),
            preserve_default=False,
        ),
    ]
