# Generated by Django 3.1.1 on 2020-09-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0021_auto_20200928_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='pib_trafico',
            name='msj_publicado',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
