# Generated by Django 3.1.7 on 2021-03-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0023_banco_notam_charly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banco_notam_charly',
        ),
    ]
