# Generated by Django 3.1.1 on 2020-10-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0035_auto_20201010_1656'),
        ('aro_ais', '0024_pib_trafico_estacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pib_registro_documento',
            fields=[
                ('id_registropib', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generado', models.DateTimeField(blank=True, null=True)),
                ('oficialaro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.trabajador')),
                ('registro', models.ManyToManyField(to='aro_ais.Pib_trafico')),
            ],
            options={
                'ordering': ['fecha_generado'],
            },
        ),
    ]
