# Generated by Django 3.1.7 on 2021-03-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0024_delete_banco_notam_charly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serie_notam',
        ),
    ]
