# Generated by Django 3.1.7 on 2021-03-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0025_delete_serie_notam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie_notam',
            fields=[
                ('serie_notam', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('serie_notam',),
            },
        ),
    ]
