# Generated by Django 3.1.7 on 2021-03-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0011_auto_20210323_1034'),
        ('aro_ais', '0026_serie_notam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco_notam_charly',
            fields=[
                ('id_datanotam', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_deposito', models.CharField(max_length=10)),
                ('indicador_remitente', models.CharField(max_length=8)),
                ('correlativo', models.CharField(max_length=7)),
                ('referencia_notam', models.CharField(max_length=8)),
                ('fir', models.CharField(max_length=4)),
                ('transito', models.CharField(max_length=2)),
                ('objetivo', models.CharField(max_length=3)),
                ('alcance', models.CharField(max_length=2)),
                ('limite_inferior', models.CharField(max_length=3)),
                ('limite_superior', models.CharField(max_length=3)),
                ('coordenadas', models.CharField(max_length=14)),
                ('desde', models.CharField(max_length=10)),
                ('hasta', models.CharField(max_length=10)),
                ('horario', models.CharField(max_length=35)),
                ('texto_notam', models.CharField(max_length=200)),
                ('limite_inferior_casilla', models.CharField(max_length=300)),
                ('limite_superior_casilla', models.CharField(max_length=300)),
                ('firma', models.CharField(max_length=20)),
                ('codigo_notam_asunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.asunto')),
                ('codigo_notam_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.estado_asunto')),
                ('direccion', models.ManyToManyField(to='aro_ais.Direccion_amhs')),
                ('indicador_prioridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.prioridad')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.aeropuerto')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.serie_notam')),
                ('tipo_notam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.tipo_notam')),
            ],
            options={
                'ordering': ('tipo_notam',),
            },
        ),
    ]
