# Generated by Django 3.1.1 on 2020-10-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0035_auto_20201010_1656'),
        ('aro_ais', '0026_auto_20201011_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pib_registro_documento',
            name='oficialaro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.trabajador'),
        ),
    ]
