# Generated by Django 3.1.7 on 2021-03-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0027_banco_notam_charly'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco_notam_charly',
            name='espaniol_decodificado',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco_notam_charly',
            name='est',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banco_notam_charly',
            name='perm',
            field=models.BooleanField(default=False),
        ),
    ]
