# Generated by Django 3.1.7 on 2021-04-10 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0028_auto_20210325_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco_notam_charly',
            options={'ordering': ('-correlativo', 'ingresado')},
        ),
        migrations.AddField(
            model_name='banco_notam_charly',
            name='ingresado',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='firma',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='hasta',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='horario',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='limite_inferior',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='limite_inferior_casilla',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='limite_superior',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='limite_superior_casilla',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='banco_notam_charly',
            name='texto_notam',
            field=models.CharField(max_length=800),
        ),
    ]
