# Generated by Django 3.1.7 on 2021-06-18 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0029_auto_20210410_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notam_trafico_alfa_cancel',
            fields=[
                ('id_mensaje_a_c', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=120)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=1200)),
                ('nuevo', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.CreateModel(
            name='Notam_trafico_alfa_new',
            fields=[
                ('id_mensaje_a_n', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=120)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=1200)),
                ('nuevo', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('cancel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aro_ais.notam_trafico_alfa_cancel')),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.CreateModel(
            name='Notam_trafico_alfa_repla',
            fields=[
                ('id_mensaje_a_r', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=120)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=1200)),
                ('nuevo', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.CreateModel(
            name='Notam_trafico_charly_cancel',
            fields=[
                ('id_mensaje_c_c', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=120)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=1200)),
                ('nuevo', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.CreateModel(
            name='Notam_trafico_charly_new',
            fields=[
                ('id_mensaje_c_n', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=120)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=1200)),
                ('es_pib', models.BooleanField(default=False)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('cancel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aro_ais.notam_trafico_charly_cancel')),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.CreateModel(
            name='Notam_trafico_charly_repla',
            fields=[
                ('id_mensaje_c_r', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=120)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=1200)),
                ('es_pib', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.DeleteModel(
            name='Banco_notam_charly',
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_new',
            name='replace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aro_ais.notam_trafico_charly_repla'),
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_new',
            name='replace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aro_ais.notam_trafico_alfa_repla'),
        ),
    ]
