# Generated by Django 3.1.7 on 2021-06-18 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0013_auto_20210410_1432'),
        ('aro_ais', '0030_auto_20210618_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notam_trafico_alfa_cancel',
            options={},
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_new',
            name='asunto',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_new',
            name='estado_asunto',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_repla',
            name='asunto',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_repla',
            name='estado_asunto',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_new',
            name='asunto',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_new',
            name='estado_asunto',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_repla',
            name='asunto',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_repla',
            name='estado_asunto',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Banco_notam_charly',
            fields=[
                ('id_datanotam', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_deposito', models.CharField(max_length=10)),
                ('indicador_remitente', models.CharField(max_length=8)),
                ('correlativo', models.CharField(max_length=7)),
                ('referencia_notam', models.CharField(max_length=8)),
                ('fir', models.CharField(max_length=4)),
                ('transito', models.CharField(max_length=2)),
                ('objetivo', models.CharField(max_length=3)),
                ('alcance', models.CharField(max_length=2)),
                ('limite_inferior', models.CharField(blank=True, max_length=3)),
                ('limite_superior', models.CharField(blank=True, max_length=3)),
                ('coordenadas', models.CharField(blank=True, max_length=14)),
                ('desde', models.CharField(max_length=10)),
                ('hasta', models.CharField(blank=True, max_length=10)),
                ('est', models.BooleanField(default=False)),
                ('perm', models.BooleanField(default=False)),
                ('horario', models.CharField(blank=True, max_length=35)),
                ('texto_notam', models.CharField(max_length=800)),
                ('limite_inferior_casilla', models.CharField(blank=True, max_length=300)),
                ('limite_superior_casilla', models.CharField(blank=True, max_length=300)),
                ('firma', models.CharField(blank=True, max_length=20)),
                ('Asunto', models.CharField(max_length=100)),
                ('espaniol_decodificado', models.CharField(max_length=1000)),
                ('ingresado', models.DateTimeField(default=datetime.datetime.now)),
                ('codigo_notam_asunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.asunto')),
                ('codigo_notam_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.estado_asunto')),
                ('direccion', models.ManyToManyField(to='aro_ais.Direccion_amhs')),
                ('indicador_prioridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.prioridad')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.aeropuerto')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.serie_notam')),
                ('tipo_notam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.tipo_notam')),
            ],
            options={
                'ordering': ('-correlativo', 'ingresado'),
            },
        ),
    ]
