# Generated by Django 3.1.1 on 2020-11-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0030_asunto_estado_asunto_letra_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asunto',
            name='fasiologia_asunto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='estado_asunto',
            name='fasiologia_estado',
            field=models.CharField(max_length=150),
        ),
    ]
