# Generated by Django 3.1.7 on 2021-06-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0031_auto_20210618_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notam_trafico_alfa_new',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='notam_trafico_alfa_new',
            name='replace',
        ),
        migrations.RemoveField(
            model_name='notam_trafico_charly_new',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='notam_trafico_charly_new',
            name='replace',
        ),
        migrations.DeleteModel(
            name='Notam_trafico_alfa_cancel',
        ),
        migrations.DeleteModel(
            name='Notam_trafico_alfa_new',
        ),
        migrations.DeleteModel(
            name='Notam_trafico_alfa_repla',
        ),
        migrations.DeleteModel(
            name='Notam_trafico_charly_cancel',
        ),
        migrations.DeleteModel(
            name='Notam_trafico_charly_new',
        ),
        migrations.DeleteModel(
            name='Notam_trafico_charly_repla',
        ),
    ]
