# Generated by Django 3.1.1 on 2020-11-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0031_auto_20201125_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letra_asunto',
            name='acronimo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
