# Generated by Django 3.1.1 on 2020-11-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0033_auto_20201125_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_asunto',
        ),
    ]
