# Generated by Django 3.1.7 on 2021-06-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0034_remove_banco_notam_charly_asunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notam_trafico_alfa_new',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='notam_trafico_alfa_new',
            name='replace',
        ),
        migrations.RemoveField(
            model_name='notam_trafico_charly_new',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='notam_trafico_charly_new',
            name='replace',
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_cancel',
            name='asunto',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_cancel',
            name='estado_asunto',
            field=models.CharField(default=123, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_cancel',
            name='asunto',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_cancel',
            name='estado_asunto',
            field=models.CharField(default=123, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_new',
            name='pib_publicar',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_repla',
            name='pib_publicar',
            field=models.CharField(default=3214, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_new',
            name='estado_asunto',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_repla',
            name='estado_asunto',
            field=models.CharField(max_length=500),
        ),
    ]
