# Generated by Django 3.1.7 on 2021-06-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0035_auto_20210623_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam_trafico_alfa_cancel',
            name='id_mensaje_a_c',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notam_trafico_alfa_new',
            name='id_mensaje_a_n',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notam_trafico_alfa_repla',
            name='id_mensaje_a_r',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_cancel',
            name='id_mensaje_c_c',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_new',
            name='id_mensaje_c_n',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_repla',
            name='id_mensaje_c_r',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
