# Generated by Django 3.1.1 on 2020-11-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0036_auto_20201125_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asunto',
            name='id_asunto',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
