# Generated by Django 3.1.1 on 2020-11-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0037_auto_20201125_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_asunto',
        ),
    ]
