# Generated by Django 3.1.1 on 2020-11-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0038_delete_estado_asunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_asunto',
            fields=[
                ('id_estado_asunto', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=350)),
                ('fasiologia_estado', models.CharField(max_length=150)),
                ('id_asunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.asunto')),
            ],
        ),
    ]
