# Generated by Django 3.1.7 on 2021-06-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0039_auto_20210624_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notam_trafico_alfa_cancel',
            name='nuevo',
        ),
        migrations.RemoveField(
            model_name='notam_trafico_alfa_new',
            name='nuevo',
        ),
        migrations.RemoveField(
            model_name='notam_trafico_alfa_repla',
            name='nuevo',
        ),
        migrations.RemoveField(
            model_name='notam_trafico_charly_cancel',
            name='nuevo',
        ),
    ]
