# Generated by Django 3.1.7 on 2021-07-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0040_auto_20210625_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='notam_trafico_alfa_cancel',
            name='antecedente',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_new',
            name='antecedente',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_repla',
            name='antecedente',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_cancel',
            name='antecedente',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_new',
            name='antecedente',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_repla',
            name='antecedente',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
