# Generated by Django 3.1.7 on 2021-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0041_auto_20210707_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='notam_trafico_charly_repla',
            name='form_oaci',
            field=models.FileField(blank=True, null=True, upload_to='documents-%Y-%m-%d/'),
        ),
    ]
