# Generated by Django 3.1.7 on 2021-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0043_auto_20210707_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_pib',
            name='lista_notam',
            field=models.CharField(max_length=20000),
        ),
    ]
