# Generated by Django 3.1.1 on 2020-12-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0044_codigo_8400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codigo_8400',
            new_name='Abreviatura_8400',
        ),
    ]
