# Generated by Django 3.1.7 on 2021-07-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0044_auto_20210707_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notam_trafico_alfa_cancel',
            options={'ordering': ['-ingresado']},
        ),
        migrations.AlterModelOptions(
            name='notam_trafico_alfa_new',
            options={'ordering': ['-ingresado']},
        ),
        migrations.AlterModelOptions(
            name='notam_trafico_alfa_repla',
            options={'ordering': ['-ingresado']},
        ),
        migrations.AlterModelOptions(
            name='notam_trafico_charly_cancel',
            options={'ordering': ['-ingresado']},
        ),
        migrations.AlterModelOptions(
            name='notam_trafico_charly_new',
            options={'ordering': ['-ingresado']},
        ),
        migrations.AlterModelOptions(
            name='notam_trafico_charly_repla',
            options={'ordering': ['-ingresado']},
        ),
        migrations.AlterField(
            model_name='historico_pib',
            name='lista_notam',
            field=models.CharField(max_length=100000),
        ),
    ]
