# Generated by Django 3.1.7 on 2021-12-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0046_auto_20211014_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='notam_trafico_alfa_cancel',
            name='correlativo_charly',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_cancel',
            name='responsable',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_new',
            name='correlativo_charly',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_new',
            name='responsable',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_repla',
            name='correlativo_charly',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_alfa_repla',
            name='responsable',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_cancel',
            name='correlativo_alfa',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_cancel',
            name='responsable',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_new',
            name='correlativo_alfa',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_new',
            name='responsable',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_repla',
            name='correlativo_alfa',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_repla',
            name='responsable',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
