# Generated by Django 3.1.1 on 2020-12-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0046_auto_20201201_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abreviatura_8400',
            name='significado_completo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='abreviatura_8400',
            name='significado_pib',
            field=models.CharField(max_length=400),
        ),
    ]
