# Generated by Django 3.1.1 on 2020-12-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0047_auto_20201201_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Significado_8400',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('significado_completo', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='asunto',
            old_name='fasiologia_asunto',
            new_name='fraseologia_asunto',
        ),
        migrations.RenameField(
            model_name='estado_asunto',
            old_name='id_asunto',
            new_name='asunto',
        ),
        migrations.RenameField(
            model_name='estado_asunto',
            old_name='fasiologia_estado',
            new_name='fraseologia_estado',
        ),
        migrations.RenameField(
            model_name='letra_asunto',
            old_name='descripcion_letra',
            new_name='titulo_letra',
        ),
        migrations.AlterField(
            model_name='abreviatura_8400',
            name='significado_completo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.significado_8400'),
        ),
    ]
