# Generated by Django 3.1.1 on 2020-12-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0048_auto_20201203_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='significado_8400',
            name='id',
        ),
        migrations.AddField(
            model_name='significado_8400',
            name='id_significado',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
