# Generated by Django 3.1.1 on 2020-12-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0057_auto_20201203_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado_asunto',
            old_name='asunto',
            new_name='id_asunto',
        ),
    ]
