# Generated by Django 3.1.1 on 2020-12-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0058_auto_20201203_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letra_asunto',
            old_name='titulo_letra',
            new_name='descripcion_letra',
        ),
    ]
