# Generated by Django 3.1.1 on 2020-12-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0060_abreviatura_8400_significado_8400_simbolo_8400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abreviatura_8400',
        ),
        migrations.DeleteModel(
            name='Significado_8400',
        ),
    ]
