# Generated by Django 3.1.1 on 2020-12-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0062_significado_8400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abreviatura_8400',
            fields=[
                ('abreviatura', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('significado_pib', models.CharField(max_length=400)),
                ('significado_completo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.significado_8400')),
                ('simbolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.simbolo_8400')),
            ],
        ),
    ]
