# Generated by Django 3.1.1 on 2020-12-03 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0063_abreviatura_8400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abreviatura_8400',
            name='significado_completo',
        ),
        migrations.RemoveField(
            model_name='abreviatura_8400',
            name='significado_pib',
        ),
        migrations.AddField(
            model_name='significado_8400',
            name='significado_pib',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
