# Generated by Django 3.1.1 on 2020-12-03 22:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0064_auto_20201203_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='significado_8400',
            name='abreviatura',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='aro_ais.abreviatura_8400'),
            preserve_default=False,
        ),
    ]
