# Generated by Django 3.1.1 on 2020-12-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0066_auto_20201203_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abreviatura_8400',
            name='abreviatura',
            field=models.CharField(max_length=550, primary_key=True, serialize=False),
        ),
    ]
