# Generated by Django 3.1.1 on 2020-12-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0067_auto_20201203_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='significado_8400',
            name='abreviatura',
        ),
        migrations.DeleteModel(
            name='Abreviatura_8400',
        ),
        migrations.DeleteModel(
            name='Significado_8400',
        ),
    ]
