# Generated by Django 2.2.5 on 2020-08-19 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadoresATS', '0002_auto_20200503_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentasats',
            name='id_trabajador',
            field=models.OneToOneField(blank=True, db_column='id_trabajador', null=True, on_delete=django.db.models.deletion.PROTECT, to='trabajadoresATS.TrabajadoresATS'),
        ),
    ]
