# Generated by Django 3.1.5 on 2021-03-01 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notam_trafico_alfa_cancel',
            fields=[
                ('id_mensaje', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=11)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=450)),
                ('nuevo', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.CreateModel(
            name='Notam_trafico_alfa_repla',
            fields=[
                ('id_mensaje', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=11)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=450)),
                ('nuevo', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.CreateModel(
            name='Notam_trafico_charly_cancel',
            fields=[
                ('id_mensaje', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=11)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=450)),
                ('nuevo', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.CreateModel(
            name='Notam_trafico_charly_repla',
            fields=[
                ('id_mensaje', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=11)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=450)),
                ('nuevo', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.CreateModel(
            name='Notam_trafico_charly_new',
            fields=[
                ('id_mensaje', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=11)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=450)),
                ('nuevo', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('cancel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.notam_trafico_charly_cancel')),
                ('replace', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.notam_trafico_charly_repla')),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
        migrations.CreateModel(
            name='Notam_trafico_alfa_new',
            fields=[
                ('id_mensaje', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=11)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=85)),
                ('resumen', models.CharField(max_length=65)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=450)),
                ('nuevo', models.BooleanField(default=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('cancel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.notam_trafico_alfa_cancel')),
                ('replace', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.notam_trafico_alfa_repla')),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
    ]
