# Generated by Django 3.1.5 on 2021-03-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0002_notam_trafico_alfa_cancel_notam_trafico_alfa_new_notam_trafico_alfa_repla_notam_trafico_charly_cance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notam_trafico_alfa_cancel',
            old_name='id_mensaje',
            new_name='id_mensaje_a_c',
        ),
        migrations.RenameField(
            model_name='notam_trafico_alfa_new',
            old_name='id_mensaje',
            new_name='id_mensaje_a_n',
        ),
        migrations.RenameField(
            model_name='notam_trafico_alfa_repla',
            old_name='id_mensaje',
            new_name='id_mensaje_a_r',
        ),
        migrations.RenameField(
            model_name='notam_trafico_charly_cancel',
            old_name='id_mensaje',
            new_name='id_mensaje_c_c',
        ),
        migrations.RenameField(
            model_name='notam_trafico_charly_new',
            old_name='id_mensaje',
            new_name='id_mensaje_c_n',
        ),
        migrations.RenameField(
            model_name='notam_trafico_charly_repla',
            old_name='id_mensaje',
            new_name='id_mensaje_c_r',
        ),
    ]
