# Generated by Django 3.1.1 on 2020-09-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0002_ruta_guardada_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta_guardada',
            name='origen',
        ),
    ]
