# Generated by Django 3.1.1 on 2020-09-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0003_remove_ruta_guardada_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta_guardada',
            name='origen',
            field=models.CharField(default='SLLL', max_length=4),
            preserve_default=False,
        ),
    ]
