# Generated by Django 3.1.1 on 2020-09-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0005_remove_ruta_guardada_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta_guardada',
            name='destino',
            field=models.CharField(default='SSSS', max_length=4),
            preserve_default=False,
        ),
    ]
