# Generated by Django 3.1.5 on 2021-03-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0005_auto_20210301_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notam_trafico_charly_repla',
            old_name='nuevo',
            new_name='es_pib',
        ),
        migrations.RemoveField(
            model_name='notam_trafico_charly_new',
            name='nuevo',
        ),
        migrations.AddField(
            model_name='notam_trafico_charly_new',
            name='es_pib',
            field=models.BooleanField(default=False),
        ),
    ]
