# Generated by Django 3.1.5 on 2021-03-09 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0006_auto_20210309_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notam_trafico_resumen',
            fields=[
                ('id_mensaje_resumen', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=15)),
                ('aftn2', models.CharField(max_length=15)),
                ('resumen', models.CharField(max_length=1000)),
                ('resumen_lista', models.CharField(blank=True, max_length=1300, null=True)),
                ('ingresado', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ('id_mensaje_resumen',),
            },
        ),
        migrations.CreateModel(
            name='Pib_tiempo_real',
            fields=[
                ('id_notam_pib', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('hora_actualizacion', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['hora_actualizacion'],
            },
        ),
    ]
