# Generated by Django 3.1.1 on 2020-09-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0006_ruta_guardada_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flp_trafico',
            name='id',
        ),
        migrations.AlterField(
            model_name='flp_trafico',
            name='id_mensaje',
            field=models.CharField(max_length=22, primary_key=True, serialize=False),
        ),
    ]
