# Generated by Django 3.1.5 on 2021-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0007_notam_trafico_resumen_pib_tiempo_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam_trafico_alfa_cancel',
            name='mensaje',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='notam_trafico_alfa_new',
            name='mensaje',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='notam_trafico_alfa_repla',
            name='mensaje',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_cancel',
            name='mensaje',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_new',
            name='mensaje',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_repla',
            name='mensaje',
            field=models.CharField(max_length=1200),
        ),
    ]
