# Generated by Django 3.1.1 on 2020-09-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0008_ruta_guardada_archivada'),
    ]

    operations = [
        migrations.AddField(
            model_name='flp_aprobado',
            name='frecuencias',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flp_aprobado',
            name='nivel',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flp_aprobado',
            name='tiempos',
            field=models.CharField(default='1000;1005', max_length=100),
            preserve_default=False,
        ),
    ]
