# Generated by Django 2.2.5 on 2021-03-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0009_flp_trafico_ingresado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aeropuerto',
            options={'ordering': ('aeropuerto',)},
        ),
    ]
