# Generated by Django 3.1.7 on 2021-03-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0010_auto_20210323_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aeropuerto',
            options={'ordering': ('icao',)},
        ),
    ]
