# Generated by Django 3.1.7 on 2021-03-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0011_auto_20210323_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flp_trafico',
            name='aftn1',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notam_trafico',
            name='aftn1',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notam_trafico_alfa_cancel',
            name='aftn1',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notam_trafico_alfa_new',
            name='aftn1',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notam_trafico_alfa_repla',
            name='aftn1',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_cancel',
            name='aftn1',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_new',
            name='aftn1',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notam_trafico_charly_repla',
            name='aftn1',
            field=models.CharField(max_length=120),
        ),
    ]
