# Generated by Django 3.1.1 on 2020-09-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0011_flp_trafico_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flp_aprobado',
            name='fecha_aprobacion',
            field=models.DateField(auto_now=True),
        ),
    ]
