# Generated by Django 3.1.7 on 2021-04-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0012_auto_20210329_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pib_tiempo_real',
            options={'ordering': ['-hora_actualizacion']},
        ),
    ]
