# Generated by Django 3.1.1 on 2020-09-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0012_auto_20200913_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flp_aprobado',
            old_name='id_flp_aprobado',
            new_name='id_flpaprobado',
        ),
    ]
