# Generated by Django 3.1.7 on 2021-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0013_auto_20210410_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='geo_ils',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='aeropuerto',
            name='geo_vor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
