# Generated by Django 3.1.7 on 2021-07-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0014_auto_20210706_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='geo_arp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
