# Generated by Django 3.1.1 on 2020-09-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0015_auto_20200914_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrepuntos_flp',
            old_name='puntoFinal',
            new_name='puntofinal',
        ),
        migrations.RenameField(
            model_name='entrepuntos_flp',
            old_name='puntoInicial',
            new_name='puntoinicial',
        ),
    ]
