# Generated by Django 3.1.7 on 2021-07-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0017_auto_20210707_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='geo_ndb',
            field=models.CharField(blank=True, default='NIL', max_length=20, null=True),
        ),
    ]
