# Generated by Django 3.1.1 on 2020-09-17 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0017_punto_satelital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Punto_satelital',
        ),
    ]
