# Generated by Django 3.1.1 on 2020-09-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0018_delete_punto_satelital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punto_satelital',
            fields=[
                ('nombrepunto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['nombrepunto'],
            },
        ),
    ]
