# Generated by Django 3.1.1 on 2020-09-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0019_punto_satelital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notam_trafico',
            fields=[
                ('id_mensaje', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('aftn1', models.CharField(max_length=11)),
                ('aftn2', models.CharField(max_length=15)),
                ('idnotam', models.CharField(max_length=40)),
                ('resumen', models.CharField(max_length=40)),
                ('aplica_a', models.CharField(max_length=15)),
                ('valido_desde', models.CharField(max_length=20)),
                ('valido_hasta', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=150)),
                ('nuevo', models.BooleanField(blank=True, default=True, null=True)),
                ('ingresado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['idnotam'],
            },
        ),
    ]
