# Generated by Django 3.1.7 on 2021-11-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0019_auto_20210707_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aeropuerto',
            old_name='geo_marcador',
            new_name='geo_mm',
        ),
    ]
