# Generated by Django 3.1.1 on 2020-09-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0025_aeropuerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam_trafico',
            name='idnotam',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='notam_trafico',
            name='mensaje',
            field=models.CharField(max_length=250),
        ),
    ]
