# Generated by Django 3.1.1 on 2020-09-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0026_auto_20200927_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam_trafico',
            name='mensaje',
            field=models.CharField(max_length=450),
        ),
    ]
