# Generated by Django 3.1.1 on 2020-11-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0038_remove_flp_aprobado_date_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='coordinador',
            field=models.BooleanField(default=False),
        ),
    ]
