# Generated by Django 3.1.1 on 2020-09-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0004_ruta_guardada_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta_guardada',
            name='destino',
        ),
    ]
