# Generated by Django 3.1.1 on 2020-09-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0007_auto_20200903_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta_guardada',
            name='archivada',
            field=models.BooleanField(default=False),
        ),
    ]
