# Generated by Django 3.1.1 on 2020-09-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0009_auto_20200912_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flp_aprobado',
            name='nivel',
            field=models.CharField(max_length=6),
        ),
    ]
