# Generated by Django 3.1.1 on 2020-09-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0010_auto_20200912_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='flp_trafico',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
