# Generated by Django 3.1.1 on 2020-09-14 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0014_auto_20200913_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flp_aprobado',
            name='controlador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan_vuelo.trabajador'),
        ),
    ]
