# Generated by Django 3.1.1 on 2020-09-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0020_notam_trafico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam_trafico',
            name='idnotam',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='notam_trafico',
            name='resumen',
            field=models.CharField(max_length=65),
        ),
    ]
