# Generated by Django 3.1.1 on 2020-09-20 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0021_auto_20200920_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam_trafico',
            name='ingresado',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
