# Generated by Django 3.1.1 on 2020-09-20 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0022_auto_20200920_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam_trafico',
            name='ingresado',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
