# Generated by Django 3.1.1 on 2020-09-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0023_auto_20200920_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam_trafico',
            name='nuevo',
            field=models.BooleanField(default=True),
        ),
    ]
