# Generated by Django 3.1.1 on 2020-10-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0030_auto_20201006_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='cuenta_usuario',
        ),
    ]
