# Generated by Django 3.1.1 on 2020-10-06 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan_vuelo', '0032_cargo_cuenta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cuenta_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
    ]
