# Generated by Django 3.1.1 on 2020-10-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0033_auto_20201006_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
