# Generated by Django 3.1.1 on 2020-10-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0034_auto_20201006_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta_flp',
            options={'ordering': ['nombre_ruta']},
        ),
    ]
