# Generated by Django 3.1.1 on 2020-10-12 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0035_auto_20201010_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='flp_aprobado',
            name='date_aprobado',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
