# Generated by Django 3.1.1 on 2020-10-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_vuelo', '0037_auto_20201012_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flp_aprobado',
            name='date_aprobado',
        ),
    ]
