# Generated by Django 3.1.1 on 2020-09-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0002_auto_20200927_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pib_trafico',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pib_trafico',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pib_trafico',
            name='vigente',
            field=models.BooleanField(default=False),
        ),
    ]
