# Generated by Django 3.1.1 on 2020-09-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0004_auto_20200927_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pib_extenso',
            fields=[
                ('notam_extenso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='aro_ais.pib_trafico')),
                ('notam_id', models.CharField(max_length=10)),
                ('notam_tipo', models.CharField(max_length=10)),
                ('ref_notam_id', models.CharField(max_length=10)),
                ('fir', models.CharField(max_length=10)),
                ('notam_codigo', models.CharField(max_length=10)),
                ('tipo_trafico', models.CharField(max_length=50)),
                ('proposito', models.CharField(max_length=200)),
                ('alcance', models.CharField(max_length=100)),
                ('fl_inferior', models.IntegerField()),
                ('fl_superior', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=50)),
                ('valid_desde', models.DateField(blank=True, null=True)),
                ('valid_hasta', models.DateField(blank=True, null=True)),
                ('agendado', models.CharField(max_length=150)),
                ('cuerpo', models.CharField(max_length=400)),
                ('limit_superior', models.CharField(max_length=10)),
                ('limit_inferior', models.CharField(max_length=10)),
                ('indices_item_a', models.CharField(max_length=15)),
                ('indices_item_b', models.CharField(max_length=15)),
                ('indices_item_c', models.CharField(max_length=15)),
                ('indices_item_d', models.CharField(max_length=15)),
                ('indices_item_e', models.CharField(max_length=15)),
                ('indices_item_f', models.CharField(max_length=15)),
                ('indices_item_g', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['notam_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='pib_trafico',
            options={'ordering': ['ref_notam_amhs']},
        ),
        migrations.RenameField(
            model_name='pib_trafico',
            old_name='pib_notam',
            new_name='ref_notam_amhs',
        ),
        migrations.RemoveField(
            model_name='pib_trafico',
            name='fin_publi',
        ),
        migrations.RemoveField(
            model_name='pib_trafico',
            name='fir',
        ),
        migrations.RemoveField(
            model_name='pib_trafico',
            name='informacion',
        ),
        migrations.RemoveField(
            model_name='pib_trafico',
            name='inicio_publi',
        ),
        migrations.RemoveField(
            model_name='pib_trafico',
            name='instalacion',
        ),
        migrations.AddField(
            model_name='pib_trafico',
            name='decodificado',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pib_trafico',
            name='publicado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
