# Generated by Django 3.1.1 on 2020-09-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0005_auto_20200927_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pib_trafico',
            name='publicado',
        ),
        migrations.AddField(
            model_name='pib_trafico',
            name='publicadofecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pib_extenso',
            name='valid_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pib_extenso',
            name='valid_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
