# Generated by Django 3.1.1 on 2020-09-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0016_pib_extenso_pib_trafico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pib_trafico',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
    ]
