# Generated by Django 3.1.1 on 2020-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0020_auto_20200928_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pib_extenso',
            name='notam_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
