# Generated by Django 3.1.1 on 2020-09-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0022_pib_trafico_msj_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pib_trafico',
            name='msj_publicado',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
