# Generated by Django 3.1.1 on 2020-10-11 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0025_pib_registro_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pib_registro_documento',
            name='fecha_generado',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
