# Generated by Django 3.1.1 on 2020-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0040_auto_20201125_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado_asunto',
            name='id_asunto',
        ),
        migrations.AddField(
            model_name='estado_asunto',
            name='id_asunto',
            field=models.ManyToManyField(to='aro_ais.Asunto'),
        ),
    ]
