# Generated by Django 3.1.1 on 2020-12-01 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0043_auto_20201201_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo_8400',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(max_length=15)),
                ('significado_completo', models.CharField(max_length=400)),
                ('significado_pib', models.CharField(max_length=300)),
                ('simbolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.simbolo_8400')),
            ],
        ),
    ]
