# Generated by Django 3.1.1 on 2020-12-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0051_auto_20201203_1920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abreviatura_8400',
        ),
        migrations.DeleteModel(
            name='Significado_8400',
        ),
        migrations.DeleteModel(
            name='Simbolo_8400',
        ),
    ]
