# Generated by Django 3.1.1 on 2020-12-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0053_abreviatura_8400_significado_8400_simbolo_8400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asunto',
            old_name='fraseologia_asunto',
            new_name='fasiologia_asunto',
        ),
        migrations.RenameField(
            model_name='estado_asunto',
            old_name='fraseologia_estado',
            new_name='fasiologia_estado',
        ),
        migrations.RenameField(
            model_name='estado_asunto',
            old_name='asunto',
            new_name='id_asunto',
        ),
        migrations.RenameField(
            model_name='letra_asunto',
            old_name='titulo_letra',
            new_name='descripcion_letra',
        ),
        migrations.AlterField(
            model_name='abreviatura_8400',
            name='significado_completo',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Significado_8400',
        ),
    ]
