# Generated by Django 3.1.1 on 2020-12-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0055_auto_20201203_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asunto',
            old_name='fraseologia_asunto',
            new_name='fasiologia_asunto',
        ),
        migrations.RenameField(
            model_name='estado_asunto',
            old_name='fraseologia_estado',
            new_name='fasiologia_estado',
        ),
    ]
