# Generated by Django 3.1.1 on 2020-12-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0061_auto_20201203_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Significado_8400',
            fields=[
                ('id_significado', models.AutoField(primary_key=True, serialize=False)),
                ('significado_completo', models.CharField(max_length=500)),
            ],
        ),
    ]
