# Generated by Django 3.1.1 on 2020-12-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0065_significado_8400_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abreviatura_8400',
            name='abreviatura',
            field=models.CharField(max_length=55, primary_key=True, serialize=False),
        ),
    ]
