# Generated by Django 3.1.1 on 2020-12-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0068_auto_20201203_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abreviatura_8400',
            fields=[
                ('abreviatura', models.CharField(max_length=550, primary_key=True, serialize=False)),
                ('simbolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.simbolo_8400')),
            ],
        ),
    ]
