# Generated by Django 3.1.1 on 2020-12-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0070_significado_8400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Significado_8400',
        ),
    ]
