# Generated by Django 3.1.1 on 2020-12-03 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0071_delete_significado_8400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Significado_8400',
            fields=[
                ('id_significado', models.AutoField(primary_key=True, serialize=False)),
                ('significado_completo', models.CharField(max_length=500)),
                ('significado_pib', models.CharField(max_length=400)),
                ('abreviatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aro_ais.abreviatura_8400')),
            ],
        ),
    ]
