# Generated by Django 3.1.1 on 2020-12-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0072_significado_8400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asunto',
            old_name='fasiologia_asunto',
            new_name='fraseologia_asunto',
        ),
        migrations.RenameField(
            model_name='estado_asunto',
            old_name='fasiologia_estado',
            new_name='fraseologia_estado',
        ),
    ]
