# Generated by Django 3.1.5 on 2021-01-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aro_ais', '0074_auto_20201204_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abreviatura_8400',
            options={'ordering': ('abreviatura',)},
        ),
        migrations.AlterModelOptions(
            name='asunto',
            options={'ordering': ('id_asunto',)},
        ),
        migrations.AlterModelOptions(
            name='estado_asunto',
            options={'ordering': ('id_estado_asunto',)},
        ),
        migrations.AlterModelOptions(
            name='letra_asunto',
            options={'ordering': ('id_letra',)},
        ),
        migrations.AlterModelOptions(
            name='simbolo_8400',
            options={'ordering': ('id_simbolo',)},
        ),
    ]
